// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iopfvgktrycujnljnexk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcGZ2Z2t0cnljdWpubGpuZXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDkwOTQsImV4cCI6MjA1Nzc4NTA5NH0.9AwypupQuFxD0ts8Jgnpv24dBpu5GgcXR-qKiHs1msY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);